name: parse a sequence using serde_yaml
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: docker.io/rust:slim-bookworm

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run test
        run: cargo test --package yaml-parse-example --lib -- test::parse_sequence_using_serde_yaml --exact --show-output
        env:
          CARGO_TERM_COLOR: always
